### ISSUE TITLE
Duplicate Transaction Reference

### ISSUE THREAD

**Issue by Alade5673** [popekabu/pay_with_paystack#16] opened 2023-12-14 18:18 UTC
I keep getting this error of duplicate transaction reference anytime I want to put in my card details. Immediately my keyboard shows up to start typing, it redirects and shows this error

below is my code

```
`PayWithPayStack().now(
        context: context,
        secretKey: '$secretKey',
        customerEmail: "$email",
        reference: DateTime.now().microsecondsSinceEpoch.toString(),
        callbackUrl: "/",
        currency: "NGN",
        paymentChannel:["card", "bank", "ussd", "qr", "mobile_money", "bank_transfer", "eft"],
        amount: couponValid == false ? "${int.parse(widget.item['amount']) * 100}" : "${(final_amount * 100).toString()}",
        transactionCompleted: () {
          print("Transaction Successful");

          setState(() {
            payment_ref = DateTime.now().microsecondsSinceEpoch.toString();
          });

          loader().showLoaderDialog(context);
          subscribe();

        },
        transactionNotCompleted: () {
          print("Transaction Not Successful!");
        });`
```
        
        
        
<img width="344" alt="Screenshot 2023-12-14 at 7 15 40 PM" src="https://github.com/popekabu/pay_with_paystack/assets/39368095/12a3e65c-b99d-4b45-b1e5-f33a5a344337">

**Comment by popekabu** [comment] 2023-12-15 06:17
The reference you’re passing from your front end isn’t changing.
Alternatively use a random string generator and see if it solves your issue

**Comment by Alade5673** [comment] 2023-12-15 06:59
It didn't 

I had to use uuid

`reference: "${DateTime.now().microsecondsSinceEpoch}_${Uuid().v4()}"`

**Comment by popekabu** [comment] 2023-12-15 07:01
That’s a strange behavior of the date time class. It’s beyond my control.
Do well to like the plugin and close the issue if it’s solved. Thank you

**Comment by popekabu** [comment] 2023-12-15 09:37
@Alade5673 how about you try a static string and see if it works then change the static string again to see if it works. I dont really know where the issue is emanating from but I suspect the dateTime class is returning the same String and since that same string is a reference id already used in your paystack. Paystack denies it. 

Also you can try restarting your app or pc or debug the datetime string and see if the string is the same or changes from time to time.

I just tested it on mine, see video below. Keep me posted.

All the best!!

https://github.com/popekabu/pay_with_paystack/assets/26738997/23ea1195-bcd4-4681-853c-a11be929aa2d

**Comment by Alade5673** [comment] 2023-12-15 12:57
@popekabu  it only happens when you want to pay with card option. Once you want to put in your card details it throws that error

**Comment by Alade5673** [comment] 2023-12-15 12:59
https://github.com/popekabu/pay_with_paystack/assets/39368095/16b81a69-1ba4-44bc-8462-151b5e140077

**Comment by Alade5673** [comment] 2023-12-16 04:35
@popekabu please can you take a look at the last video I sent?

**Comment by Alade5673** [comment] 2023-12-16 21:07
@popekabu

**Comment by popekabu** [comment] 2023-12-16 21:13
Will do if I have the time. Thanks

**Comment by popekabu** [comment] 2023-12-20 08:26
@Alade5673 I had a look at your video the day you posted it, Im not sure where the issue is from. Might be a paystack issue

**Comment by Alade5673** [comment] 2023-12-21 13:40
alright no problem

thanks

**Comment by popekabu** [comment] 2023-12-21 13:53
To be safe too. Be sure your using uuidv4 as your reference and not dateTime. Initialize it in the parameter directly. Please keep me posted on what happens from there.

Thanks

**Comment by popekabu** [comment] 2024-06-20 09:04
try using uuid as a unique id generator. Get it from pub.dev

**Closed by popekabu** 2024-06-20 09:04 UTC
